name: words_freq_meter
description: Tool for measuring words frequency.

version: 1.0.0

environment:
  sdk: ^3.0.1

dependencies:
  http: ^1.0.0
  collection: ^1.17.2

dev_dependencies:
  lints: ^2.0.0
